#Michael Blumenshine
#Makefile for HW6
#C++
#Due: 19 February 2015

all: HW6-1 HW6-2 HW6-3 HW6-4

HW6-1: HW6-1.cpp
	g++ -std=gnu++11 -Wall -o HW6-1 HW6-1.cpp
	
HW6-2: HW6-2.cpp
	g++ -std=gnu++11 -Wall -o HW6-2 HW6-2.cpp
	
HW6-3: HW6-3.cpp
	g++ -std=gnu++11 -Wall -o HW6-3 HW6-3.cpp -lboost_system -lboost_filesystem -fopenmp
	
HW6-4: HW6-4.cpp
	g++ -std=gnu++11 -Wall -o HW6-4 HW6-4.cpp -lboost_system -lboost_filesystem

