#makefile for HW 8
#Michael Blumenshine

all: HW8-1 HW8-2 HW8-3

HW8-1: HW8-1.cpp
	g++ -std=c++11 -o HW8-1 HW8-1.cpp -pthread
	
HW8-2: HW8-2.cpp
	g++ -std=c++11 -o HW8-2 HW8-2.cpp -pthread -mcx16

HW8-3: HW8-3.cpp
	g++ -std=c++11 -o HW8-3 HW8-3.cpp -fopenmp
