# Michael Blumenshine
# Makefile for HW2

all: HW2-1 HW2-2 HW2-3 HW2-4 HW2-5

HW2-1: HW2-1.cpp
	g++ -std=c++11 -o HW2-1 HW2-1.cpp

HW2-2: HW2-2.cpp
	g++ -std=c++11 -o HW2-2 HW2-2.cpp
	
HW2-3: HW2-3.cpp
	g++ -std=c++11 -o HW2-3 HW2-3.cpp

HW2-4: HW2-4.cpp
	g++ -std=c++11 -o HW2-4 HW2-4.cpp triangle.cpp row.cpp
	
HW2-5: HW2-5.cpp
	g++ -std=c++11 -o HW2-5 HW2-5.cpp
