# Michael Blumenshine
# Makefile for HW3

all: HW3-1 HW3-2 HW3-3 HW3-5 HW3-6

HW3-1: HW3-1.cpp
	g++ -std=c++11 -o HW3-1 HW3-1.cpp

HW3-2: HW3-2.cpp
	g++ -std=c++11 -o HW3-2 HW3-2.cpp
	
HW3-3: HW3-3.cpp
	g++ -std=c++11 -o HW3-3 HW3-3.cpp
	
HW3-5: HW3-5.cpp
	g++ -std=c++11 -o HW3-5 HW3-5.cpp
	
HW3-6: HW3-6.cpp
	g++ -std=c++11 -o HW3-6 HW3-6.cpp
