#Michael Blumenshine
#Makefile for HW5
#C++
#Due: 12 February 2015

all: HW5-1 Matrix OverloadMatrix PSMatrix HW5-4

HW5-1: HW5-1.cpp
	g++ -std=gnu++11 -Wall -o HW5-1 HW5-1.cpp
	
Matrix: Matrix.cpp
	g++ -std=gnu++11 -Wall -o Matrix Matrix.cpp
	
OverloadMatrix: OverloadMatrix.cpp
	g++ -std=gnu++11 -Wall -o OverloadMatrix OverloadMatrix.cpp
	
PSMatrix: PSMatrix.cpp
	g++ -std=gnu++11 -Wall -o PSMatrix PSMatrix.cpp

HW5-4: HW5-4.cpp
	g++ -std=gnu++11 -Wall -o HW5-4 HW5-4.cpp
